# Generated by Django 5.0 on 2024-11-05 19:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator('^\\d{8}$', message='El DNI debe tener 8 dígitos.')], verbose_name='DNI')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('telefono', models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator('^\\+(?:\\d{1,3}\\s)?\\d{10,12}$|^\\(\\d{3}\\)\\s?\\d{3}-\\d{4}$', message='Número de teléfono inválido.')], verbose_name='Teléfono')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('genero', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('O', 'Otro')], default='F', max_length=1)),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
            },
        ),
    ]
