# Generated by Django 5.0 on 2024-12-14 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'categiria',
                'verbose_name_plural': 'categorias',
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'color',
                'verbose_name_plural': 'colores',
                'db_table': 'color',
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('provincia', models.CharField(max_length=20, verbose_name='Provincia')),
            ],
            options={
                'verbose_name': 'localidad',
                'verbose_name_plural': 'localidades',
                'db_table': 'localidad',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('telefono', models.CharField(blank=True, max_length=12, verbose_name='Teléfono')),
                ('direccion', models.CharField(blank=True, max_length=50, verbose_name='Dirección')),
                ('dni', models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='DNI')),
                ('genero', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('O', 'Otro')], default='F', max_length=1)),
                ('observacion', models.CharField(blank=True, max_length=400, verbose_name='Observación')),
                ('localidad', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Localidad', to='alquiler.localidad')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Pantalon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talle_pantalon', models.CharField(blank=True, max_length=20, null=True)),
                ('color_pantalon', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='alquiler.color')),
            ],
            options={
                'verbose_name': 'pantalon',
                'verbose_name_plural': 'pantalones',
                'db_table': 'pantalon',
            },
        ),
        migrations.CreateModel(
            name='Prenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, max_length=60, null=True)),
                ('busto', models.IntegerField(blank=True, null=True)),
                ('cintura', models.IntegerField(blank=True, null=True)),
                ('cadera', models.IntegerField(blank=True, null=True)),
                ('largo', models.IntegerField(blank=True, null=True, verbose_name='Largo(cm)')),
                ('talle', models.CharField(blank=True, max_length=20, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquiler.categoria')),
                ('color', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='alquiler.color')),
                ('relacionadas', models.ManyToManyField(blank=True, to='alquiler.prenda', verbose_name='Relacionadas')),
            ],
            options={
                'verbose_name': 'prenda',
                'verbose_name_plural': 'prendas',
                'db_table': 'prenda',
            },
        ),
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alquiler', models.DateField(auto_now_add=True)),
                ('fecha_devolucion', models.DateField()),
                ('precio_alquiler', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('reservado', 'Reservado'), ('alquilado', 'Alquilado'), ('devuelto', 'Devuelto'), ('limpieza', 'Limpieza')], default='alquilado', max_length=20)),
                ('seña', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquiler.cliente')),
                ('prenda', models.ManyToManyField(to='alquiler.prenda')),
            ],
            options={
                'verbose_name': 'alquiler',
                'verbose_name_plural': 'alquileres',
                'db_table': 'alquiler',
            },
        ),
        migrations.CreateModel(
            name='Saco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talle_saco', models.CharField(blank=True, max_length=20, null=True)),
                ('color_saco', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='alquiler.color')),
            ],
            options={
                'verbose_name': 'saco',
                'verbose_name_plural': 'sacos',
                'db_table': 'saco',
            },
        ),
        migrations.CreateModel(
            name='Traje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_articulo', models.CharField(max_length=20, unique=True)),
                ('pantalon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='alquiler.pantalon')),
                ('saco', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='alquiler.saco')),
            ],
            options={
                'verbose_name': 'traje',
                'verbose_name_plural': 'trajes',
                'db_table': 'traje',
            },
        ),
    ]
