# Generated by Django 5.0 on 2024-11-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='observacion',
            field=models.CharField(blank=True, max_length=400, verbose_name='Observación'),
        ),
    ]
