# Generated by Django 5.0 on 2024-12-14 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='pantalon',
            field=models.ManyToManyField(blank=True, to='alquiler.pantalon'),
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='prenda',
            field=models.ManyToManyField(blank=True, to='alquiler.prenda'),
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='traje',
            field=models.ManyToManyField(blank=True, to='alquiler.traje'),
        ),
    ]
