# Generated by Django 5.0 on 2024-12-14 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alquiler',
            name='fecha_devolucion',
        ),
        migrations.AddField(
            model_name='alquiler',
            name='traje',
            field=models.ManyToManyField(to='alquiler.traje'),
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='estado',
            field=models.CharField(choices=[('reservado', 'Reservado'), ('alquilado', 'Alquilado'), ('limpieza', 'Limpieza')], default='alquilado', max_length=20),
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='fecha_alquiler',
            field=models.DateField(),
        ),
    ]
