# Generated by Django 5.0 on 2024-11-23 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0002_cliente_observacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('busto', models.IntegerField(blank=True, null=True)),
                ('cintura', models.IntegerField(blank=True, null=True)),
                ('cadera', models.IntegerField(blank=True, null=True)),
                ('talle', models.CharField(blank=True, max_length=20, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquiler.categoria')),
            ],
            options={
                'verbose_name': 'prenda',
                'verbose_name_plural': 'prendas',
                'db_table': 'prenda',
            },
        ),
    ]
