# Generated by Django 5.0 on 2024-11-29 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0002_alter_categoria_options_alter_localidad_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Desconocido', max_length=100)),
            ],
            options={
                'verbose_name': 'color',
                'verbose_name_plural': 'colores',
                'db_table': 'color',
            },
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'cliente', 'verbose_name_plural': 'clientes'},
        ),
        migrations.RemoveField(
            model_name='prenda',
            name='id',
        ),
        migrations.RemoveField(
            model_name='prenda',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='prenda',
            name='precio',
        ),
        migrations.AddField(
            model_name='prenda',
            name='largo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Largo(cm)'),
        ),
        migrations.AddField(
            model_name='prenda',
            name='nro_articulo',
            field=models.CharField(default=1, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='prenda',
            name='relacionadas',
            field=models.ManyToManyField(blank=True, to='alquiler.prenda', verbose_name='Relacionadas'),
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquiler.cliente'),
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='estado',
            field=models.CharField(choices=[('reservado', 'Reservado'), ('alquilado', 'Alquilado'), ('devuelto', 'Devuelto'), ('limpieza', 'Limpieza')], default='alquilado', max_length=20),
        ),
        migrations.RemoveField(
            model_name='alquiler',
            name='prenda',
        ),
        migrations.AddField(
            model_name='prenda',
            name='color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='alquiler.color'),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='prenda',
            field=models.ManyToManyField(to='alquiler.prenda'),
        ),
    ]
