# Generated by Django 5.0 on 2024-12-14 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0002_alter_alquiler_pantalon_alter_alquiler_prenda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='saco',
            field=models.ManyToManyField(blank=True, to='alquiler.saco'),
        ),
    ]
