# Generated by Django 5.0 on 2024-12-14 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0003_alter_alquiler_saco'),
    ]

    operations = [
        migrations.AddField(
            model_name='pantalon',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='prenda',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='saco',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
