# Generated by Django 5.0 on 2024-11-29 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0003_color_alter_cliente_options_remove_prenda_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenda',
            name='nro_articulo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
