# Generated by Django 5.0 on 2024-12-14 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0004_pantalon_disponible_prenda_disponible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='seña',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
