# Generated by Django 5.0 on 2024-12-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0006_alquiler_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenda',
            name='descripcion',
            field=models.TextField(blank=True, max_length=60, null=True),
        ),
    ]
