# Generated by Django 5.1.6 on 2025-02-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0007_pantalon_reparacion_pantalon_tintoreria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='estado',
            field=models.CharField(choices=[('reservado', 'Reservado'), ('alquilado', 'Alquilado'), ('devuelto', 'Devuelto')], default='reservado', max_length=20),
        ),
    ]
