# Generated by Django 5.1.6 on 2025-02-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0009_traje_prendas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alquiler',
            name='pantalon',
        ),
        migrations.RemoveField(
            model_name='alquiler',
            name='saco',
        ),
        migrations.AddField(
            model_name='alquiler',
            name='fecha_devolucion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
