# Generated by Django 5.1.6 on 2025-02-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0010_remove_alquiler_pantalon_remove_alquiler_saco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='prenda',
            field=models.ManyToManyField(blank=True, related_name='alquileres', to='alquiler.prenda'),
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='traje',
            field=models.ManyToManyField(blank=True, related_name='alquileres', to='alquiler.traje'),
        ),
    ]
