# Generated by Django 5.1.6 on 2025-02-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0011_alter_alquiler_prenda_alter_alquiler_traje'),
    ]

    operations = [
        migrations.AddField(
            model_name='traje',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
